/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import * as Context from "./src/context"
import * as photon from "@prisma/photon"



declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  TrumpAttributeCreateInput: { // input type
    aimHigh?: boolean | null; // Boolean
    id?: string | null; // ID
    name: string; // String!
    pack: NexusGenInputs['TrumpPackCreateOneWithoutPackInput']; // TrumpPackCreateOneWithoutPackInput!
    trumpAttributeValues?: NexusGenInputs['TrumpAttributeValueCreateManyWithoutTrumpAttributeValuesInput'] | null; // TrumpAttributeValueCreateManyWithoutTrumpAttributeValuesInput
  }
  TrumpAttributeCreateManyWithoutAttributesInput: { // input type
    connect?: NexusGenInputs['TrumpAttributeWhereUniqueInput'][] | null; // [TrumpAttributeWhereUniqueInput!]
    create?: NexusGenInputs['TrumpAttributeCreateWithoutPackInput'][] | null; // [TrumpAttributeCreateWithoutPackInput!]
  }
  TrumpAttributeCreateOneWithoutAttributeInput: { // input type
    connect?: NexusGenInputs['TrumpAttributeWhereUniqueInput'] | null; // TrumpAttributeWhereUniqueInput
    create?: NexusGenInputs['TrumpAttributeCreateWithoutTrumpAttributeValuesInput'] | null; // TrumpAttributeCreateWithoutTrumpAttributeValuesInput
  }
  TrumpAttributeCreateWithoutPackInput: { // input type
    aimHigh?: boolean | null; // Boolean
    id?: string | null; // ID
    name: string; // String!
    trumpAttributeValues?: NexusGenInputs['TrumpAttributeValueCreateManyWithoutTrumpAttributeValuesInput'] | null; // TrumpAttributeValueCreateManyWithoutTrumpAttributeValuesInput
  }
  TrumpAttributeCreateWithoutTrumpAttributeValuesInput: { // input type
    aimHigh?: boolean | null; // Boolean
    id?: string | null; // ID
    name: string; // String!
    pack: NexusGenInputs['TrumpPackCreateOneWithoutPackInput']; // TrumpPackCreateOneWithoutPackInput!
  }
  TrumpAttributeValueCreateManyWithoutAttributeValuesInput: { // input type
    connect?: NexusGenInputs['TrumpAttributeValueWhereUniqueInput'][] | null; // [TrumpAttributeValueWhereUniqueInput!]
    create?: NexusGenInputs['TrumpAttributeValueCreateWithoutCardInput'][] | null; // [TrumpAttributeValueCreateWithoutCardInput!]
  }
  TrumpAttributeValueCreateManyWithoutTrumpAttributeValuesInput: { // input type
    connect?: NexusGenInputs['TrumpAttributeValueWhereUniqueInput'][] | null; // [TrumpAttributeValueWhereUniqueInput!]
    create?: NexusGenInputs['TrumpAttributeValueCreateWithoutAttributeInput'][] | null; // [TrumpAttributeValueCreateWithoutAttributeInput!]
  }
  TrumpAttributeValueCreateWithoutAttributeInput: { // input type
    card: NexusGenInputs['TrumpCardCreateOneWithoutCardInput']; // TrumpCardCreateOneWithoutCardInput!
    id?: string | null; // ID
    value: number; // Float!
  }
  TrumpAttributeValueCreateWithoutCardInput: { // input type
    attribute: NexusGenInputs['TrumpAttributeCreateOneWithoutAttributeInput']; // TrumpAttributeCreateOneWithoutAttributeInput!
    id?: string | null; // ID
    value: number; // Float!
  }
  TrumpAttributeValueWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
  TrumpAttributeWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
  TrumpCardCreateInput: { // input type
    attributeValues?: NexusGenInputs['TrumpAttributeValueCreateManyWithoutAttributeValuesInput'] | null; // TrumpAttributeValueCreateManyWithoutAttributeValuesInput
    description?: string | null; // String
    id?: string | null; // ID
    imageUrl?: string | null; // String
    name: string; // String!
    pack: NexusGenInputs['TrumpPackCreateOneWithoutPackInput']; // TrumpPackCreateOneWithoutPackInput!
  }
  TrumpCardCreateManyWithoutCardsInput: { // input type
    connect?: NexusGenInputs['TrumpCardWhereUniqueInput'][] | null; // [TrumpCardWhereUniqueInput!]
    create?: NexusGenInputs['TrumpCardCreateWithoutPackInput'][] | null; // [TrumpCardCreateWithoutPackInput!]
  }
  TrumpCardCreateOneWithoutCardInput: { // input type
    connect?: NexusGenInputs['TrumpCardWhereUniqueInput'] | null; // TrumpCardWhereUniqueInput
    create?: NexusGenInputs['TrumpCardCreateWithoutAttributeValuesInput'] | null; // TrumpCardCreateWithoutAttributeValuesInput
  }
  TrumpCardCreateWithoutAttributeValuesInput: { // input type
    description?: string | null; // String
    id?: string | null; // ID
    imageUrl?: string | null; // String
    name: string; // String!
    pack: NexusGenInputs['TrumpPackCreateOneWithoutPackInput']; // TrumpPackCreateOneWithoutPackInput!
  }
  TrumpCardCreateWithoutPackInput: { // input type
    attributeValues?: NexusGenInputs['TrumpAttributeValueCreateManyWithoutAttributeValuesInput'] | null; // TrumpAttributeValueCreateManyWithoutAttributeValuesInput
    description?: string | null; // String
    id?: string | null; // ID
    imageUrl?: string | null; // String
    name: string; // String!
  }
  TrumpCardWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
  TrumpGameCreateManyWithoutTrumpGamesAtTurnInput: { // input type
    connect?: NexusGenInputs['TrumpGameWhereUniqueInput'][] | null; // [TrumpGameWhereUniqueInput!]
    create?: NexusGenInputs['TrumpGameCreateWithoutPlayerAtTurnInput'][] | null; // [TrumpGameCreateWithoutPlayerAtTurnInput!]
  }
  TrumpGameCreateManyWithoutTrumpGamesInput: { // input type
    connect?: NexusGenInputs['TrumpGameWhereUniqueInput'][] | null; // [TrumpGameWhereUniqueInput!]
    create?: NexusGenInputs['TrumpGameCreateWithoutPlayersInput'][] | null; // [TrumpGameCreateWithoutPlayersInput!]
  }
  TrumpGameCreateWithoutPlayerAtTurnInput: { // input type
    id?: string | null; // ID
    pack: NexusGenInputs['TrumpPackCreateOneWithoutPackInput']; // TrumpPackCreateOneWithoutPackInput!
    players?: NexusGenInputs['TrumpPlayerCreateManyWithoutPlayersInput'] | null; // TrumpPlayerCreateManyWithoutPlayersInput
  }
  TrumpGameCreateWithoutPlayersInput: { // input type
    id?: string | null; // ID
    pack: NexusGenInputs['TrumpPackCreateOneWithoutPackInput']; // TrumpPackCreateOneWithoutPackInput!
    playerAtTurn?: NexusGenInputs['TrumpPlayerCreateOneWithoutPlayerAtTurnInput'] | null; // TrumpPlayerCreateOneWithoutPlayerAtTurnInput
  }
  TrumpGameWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
  TrumpPackCreateInput: { // input type
    attributes?: NexusGenInputs['TrumpAttributeCreateManyWithoutAttributesInput'] | null; // TrumpAttributeCreateManyWithoutAttributesInput
    author: NexusGenInputs['TrumpPlayerCreateOneWithoutAuthorInput']; // TrumpPlayerCreateOneWithoutAuthorInput!
    cards?: NexusGenInputs['TrumpCardCreateManyWithoutCardsInput'] | null; // TrumpCardCreateManyWithoutCardsInput
    createdAt?: any | null; // DateTime
    description: string; // String!
    id?: string | null; // ID
    name: string; // String!
    trumpGames?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesInput
    updatedAt?: any | null; // DateTime
  }
  TrumpPackCreateManyWithoutTrumpPacksInput: { // input type
    connect?: NexusGenInputs['TrumpPackWhereUniqueInput'][] | null; // [TrumpPackWhereUniqueInput!]
    create?: NexusGenInputs['TrumpPackCreateWithoutAuthorInput'][] | null; // [TrumpPackCreateWithoutAuthorInput!]
  }
  TrumpPackCreateOneWithoutPackInput: { // input type
    connect?: NexusGenInputs['TrumpPackWhereUniqueInput'] | null; // TrumpPackWhereUniqueInput
    create?: NexusGenInputs['TrumpPackCreateWithoutAttributesInput'] | null; // TrumpPackCreateWithoutAttributesInput
  }
  TrumpPackCreateWithoutAttributesInput: { // input type
    author: NexusGenInputs['TrumpPlayerCreateOneWithoutAuthorInput']; // TrumpPlayerCreateOneWithoutAuthorInput!
    cards?: NexusGenInputs['TrumpCardCreateManyWithoutCardsInput'] | null; // TrumpCardCreateManyWithoutCardsInput
    createdAt?: any | null; // DateTime
    description: string; // String!
    id?: string | null; // ID
    name: string; // String!
    trumpGames?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesInput
    updatedAt?: any | null; // DateTime
  }
  TrumpPackCreateWithoutAuthorInput: { // input type
    attributes?: NexusGenInputs['TrumpAttributeCreateManyWithoutAttributesInput'] | null; // TrumpAttributeCreateManyWithoutAttributesInput
    cards?: NexusGenInputs['TrumpCardCreateManyWithoutCardsInput'] | null; // TrumpCardCreateManyWithoutCardsInput
    createdAt?: any | null; // DateTime
    description: string; // String!
    id?: string | null; // ID
    name: string; // String!
    trumpGames?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesInput
    updatedAt?: any | null; // DateTime
  }
  TrumpPackWhereUniqueInput: { // input type
    id?: string | null; // ID
    name?: string | null; // String
  }
  TrumpPlayerCreateManyWithoutPlayersInput: { // input type
    connect?: NexusGenInputs['TrumpPlayerWhereUniqueInput'][] | null; // [TrumpPlayerWhereUniqueInput!]
    create?: NexusGenInputs['TrumpPlayerCreateWithoutTrumpGamesInput'][] | null; // [TrumpPlayerCreateWithoutTrumpGamesInput!]
  }
  TrumpPlayerCreateOneWithoutAuthorInput: { // input type
    connect?: NexusGenInputs['TrumpPlayerWhereUniqueInput'] | null; // TrumpPlayerWhereUniqueInput
    create?: NexusGenInputs['TrumpPlayerCreateWithoutTrumpPacksInput'] | null; // TrumpPlayerCreateWithoutTrumpPacksInput
  }
  TrumpPlayerCreateOneWithoutPlayerAtTurnInput: { // input type
    connect?: NexusGenInputs['TrumpPlayerWhereUniqueInput'] | null; // TrumpPlayerWhereUniqueInput
    create?: NexusGenInputs['TrumpPlayerCreateWithoutTrumpGamesAtTurnInput'] | null; // TrumpPlayerCreateWithoutTrumpGamesAtTurnInput
  }
  TrumpPlayerCreateOneWithoutTrumpPlayerInput: { // input type
    connect?: NexusGenInputs['TrumpPlayerWhereUniqueInput'] | null; // TrumpPlayerWhereUniqueInput
    create?: NexusGenInputs['TrumpPlayerCreateWithoutUserInput'] | null; // TrumpPlayerCreateWithoutUserInput
  }
  TrumpPlayerCreateWithoutTrumpGamesAtTurnInput: { // input type
    id?: string | null; // ID
    trumpGames?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesInput
    trumpPacks?: NexusGenInputs['TrumpPackCreateManyWithoutTrumpPacksInput'] | null; // TrumpPackCreateManyWithoutTrumpPacksInput
    user: NexusGenInputs['UserCreateOneWithoutUserInput']; // UserCreateOneWithoutUserInput!
  }
  TrumpPlayerCreateWithoutTrumpGamesInput: { // input type
    id?: string | null; // ID
    trumpGamesAtTurn?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesAtTurnInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesAtTurnInput
    trumpPacks?: NexusGenInputs['TrumpPackCreateManyWithoutTrumpPacksInput'] | null; // TrumpPackCreateManyWithoutTrumpPacksInput
    user: NexusGenInputs['UserCreateOneWithoutUserInput']; // UserCreateOneWithoutUserInput!
  }
  TrumpPlayerCreateWithoutTrumpPacksInput: { // input type
    id?: string | null; // ID
    trumpGames?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesInput
    trumpGamesAtTurn?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesAtTurnInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesAtTurnInput
    user: NexusGenInputs['UserCreateOneWithoutUserInput']; // UserCreateOneWithoutUserInput!
  }
  TrumpPlayerCreateWithoutUserInput: { // input type
    id?: string | null; // ID
    trumpGames?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesInput
    trumpGamesAtTurn?: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesAtTurnInput'] | null; // TrumpGameCreateManyWithoutTrumpGamesAtTurnInput
    trumpPacks?: NexusGenInputs['TrumpPackCreateManyWithoutTrumpPacksInput'] | null; // TrumpPackCreateManyWithoutTrumpPacksInput
  }
  TrumpPlayerWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
  UserCreateInput: { // input type
    email: string; // String!
    id?: string | null; // ID
    name: string; // String!
    trumpPlayer?: NexusGenInputs['TrumpPlayerCreateOneWithoutTrumpPlayerInput'] | null; // TrumpPlayerCreateOneWithoutTrumpPlayerInput
  }
  UserCreateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutTrumpPlayerInput'] | null; // UserCreateWithoutTrumpPlayerInput
  }
  UserCreateWithoutTrumpPlayerInput: { // input type
    email: string; // String!
    id?: string | null; // ID
    name: string; // String!
  }
  UserWhereUniqueInput: { // input type
    id?: string | null; // ID
  }
}

export interface NexusGenEnums {
}

export interface NexusGenRootTypes {
  Mutation: {};
  Query: {};
  Subscription: { // root type
    createdTrumpGame: NexusGenRootTypes['TrumpGame']; // TrumpGame!
  }
  TrumpAttribute: photon.TrumpAttribute;
  TrumpAttributeValue: photon.TrumpAttributeValue;
  TrumpCard: photon.TrumpCard;
  TrumpGame: photon.TrumpGame;
  TrumpPack: photon.TrumpPack;
  TrumpPlayer: photon.TrumpPlayer;
  User: photon.User;
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  DateTime: any;
  Upload: any;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  TrumpAttributeCreateInput: NexusGenInputs['TrumpAttributeCreateInput'];
  TrumpAttributeCreateManyWithoutAttributesInput: NexusGenInputs['TrumpAttributeCreateManyWithoutAttributesInput'];
  TrumpAttributeCreateOneWithoutAttributeInput: NexusGenInputs['TrumpAttributeCreateOneWithoutAttributeInput'];
  TrumpAttributeCreateWithoutPackInput: NexusGenInputs['TrumpAttributeCreateWithoutPackInput'];
  TrumpAttributeCreateWithoutTrumpAttributeValuesInput: NexusGenInputs['TrumpAttributeCreateWithoutTrumpAttributeValuesInput'];
  TrumpAttributeValueCreateManyWithoutAttributeValuesInput: NexusGenInputs['TrumpAttributeValueCreateManyWithoutAttributeValuesInput'];
  TrumpAttributeValueCreateManyWithoutTrumpAttributeValuesInput: NexusGenInputs['TrumpAttributeValueCreateManyWithoutTrumpAttributeValuesInput'];
  TrumpAttributeValueCreateWithoutAttributeInput: NexusGenInputs['TrumpAttributeValueCreateWithoutAttributeInput'];
  TrumpAttributeValueCreateWithoutCardInput: NexusGenInputs['TrumpAttributeValueCreateWithoutCardInput'];
  TrumpAttributeValueWhereUniqueInput: NexusGenInputs['TrumpAttributeValueWhereUniqueInput'];
  TrumpAttributeWhereUniqueInput: NexusGenInputs['TrumpAttributeWhereUniqueInput'];
  TrumpCardCreateInput: NexusGenInputs['TrumpCardCreateInput'];
  TrumpCardCreateManyWithoutCardsInput: NexusGenInputs['TrumpCardCreateManyWithoutCardsInput'];
  TrumpCardCreateOneWithoutCardInput: NexusGenInputs['TrumpCardCreateOneWithoutCardInput'];
  TrumpCardCreateWithoutAttributeValuesInput: NexusGenInputs['TrumpCardCreateWithoutAttributeValuesInput'];
  TrumpCardCreateWithoutPackInput: NexusGenInputs['TrumpCardCreateWithoutPackInput'];
  TrumpCardWhereUniqueInput: NexusGenInputs['TrumpCardWhereUniqueInput'];
  TrumpGameCreateManyWithoutTrumpGamesAtTurnInput: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesAtTurnInput'];
  TrumpGameCreateManyWithoutTrumpGamesInput: NexusGenInputs['TrumpGameCreateManyWithoutTrumpGamesInput'];
  TrumpGameCreateWithoutPlayerAtTurnInput: NexusGenInputs['TrumpGameCreateWithoutPlayerAtTurnInput'];
  TrumpGameCreateWithoutPlayersInput: NexusGenInputs['TrumpGameCreateWithoutPlayersInput'];
  TrumpGameWhereUniqueInput: NexusGenInputs['TrumpGameWhereUniqueInput'];
  TrumpPackCreateInput: NexusGenInputs['TrumpPackCreateInput'];
  TrumpPackCreateManyWithoutTrumpPacksInput: NexusGenInputs['TrumpPackCreateManyWithoutTrumpPacksInput'];
  TrumpPackCreateOneWithoutPackInput: NexusGenInputs['TrumpPackCreateOneWithoutPackInput'];
  TrumpPackCreateWithoutAttributesInput: NexusGenInputs['TrumpPackCreateWithoutAttributesInput'];
  TrumpPackCreateWithoutAuthorInput: NexusGenInputs['TrumpPackCreateWithoutAuthorInput'];
  TrumpPackWhereUniqueInput: NexusGenInputs['TrumpPackWhereUniqueInput'];
  TrumpPlayerCreateManyWithoutPlayersInput: NexusGenInputs['TrumpPlayerCreateManyWithoutPlayersInput'];
  TrumpPlayerCreateOneWithoutAuthorInput: NexusGenInputs['TrumpPlayerCreateOneWithoutAuthorInput'];
  TrumpPlayerCreateOneWithoutPlayerAtTurnInput: NexusGenInputs['TrumpPlayerCreateOneWithoutPlayerAtTurnInput'];
  TrumpPlayerCreateOneWithoutTrumpPlayerInput: NexusGenInputs['TrumpPlayerCreateOneWithoutTrumpPlayerInput'];
  TrumpPlayerCreateWithoutTrumpGamesAtTurnInput: NexusGenInputs['TrumpPlayerCreateWithoutTrumpGamesAtTurnInput'];
  TrumpPlayerCreateWithoutTrumpGamesInput: NexusGenInputs['TrumpPlayerCreateWithoutTrumpGamesInput'];
  TrumpPlayerCreateWithoutTrumpPacksInput: NexusGenInputs['TrumpPlayerCreateWithoutTrumpPacksInput'];
  TrumpPlayerCreateWithoutUserInput: NexusGenInputs['TrumpPlayerCreateWithoutUserInput'];
  TrumpPlayerWhereUniqueInput: NexusGenInputs['TrumpPlayerWhereUniqueInput'];
  UserCreateInput: NexusGenInputs['UserCreateInput'];
  UserCreateOneWithoutUserInput: NexusGenInputs['UserCreateOneWithoutUserInput'];
  UserCreateWithoutTrumpPlayerInput: NexusGenInputs['UserCreateWithoutTrumpPlayerInput'];
  UserWhereUniqueInput: NexusGenInputs['UserWhereUniqueInput'];
}

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createOneTrumpAttribute: NexusGenRootTypes['TrumpAttribute']; // TrumpAttribute!
    createOneTrumpCard: NexusGenRootTypes['TrumpCard']; // TrumpCard!
    createOneTrumpPack: NexusGenRootTypes['TrumpPack']; // TrumpPack!
    createOneUser: NexusGenRootTypes['User']; // User!
    startTrumpGame: NexusGenRootTypes['TrumpGame']; // TrumpGame!
    uploadTrumpCardImage: boolean; // Boolean!
  }
  Query: { // field return type
    trumpGames: NexusGenRootTypes['TrumpGame'][]; // [TrumpGame!]!
    trumpPacks: NexusGenRootTypes['TrumpPack'][]; // [TrumpPack!]!
    trumpPlayers: NexusGenRootTypes['TrumpPlayer'][]; // [TrumpPlayer!]!
    user: NexusGenRootTypes['User'] | null; // User
  }
  Subscription: { // field return type
    createdTrumpGame: NexusGenRootTypes['TrumpGame']; // TrumpGame!
  }
  TrumpAttribute: { // field return type
    aimHigh: boolean; // Boolean!
    id: string; // ID!
    name: string; // String!
    pack: NexusGenRootTypes['TrumpPack']; // TrumpPack!
  }
  TrumpAttributeValue: { // field return type
    attribute: NexusGenRootTypes['TrumpAttribute']; // TrumpAttribute!
    card: NexusGenRootTypes['TrumpCard']; // TrumpCard!
    id: string; // ID!
    value: number; // Float!
  }
  TrumpCard: { // field return type
    attributeValues: NexusGenRootTypes['TrumpAttributeValue'][]; // [TrumpAttributeValue!]!
    description: string | null; // String
    id: string; // ID!
    imageUrl: string | null; // String
    name: string; // String!
    pack: NexusGenRootTypes['TrumpPack']; // TrumpPack!
  }
  TrumpGame: { // field return type
    id: string; // ID!
    pack: NexusGenRootTypes['TrumpPack']; // TrumpPack!
    playerAtTurn: NexusGenRootTypes['TrumpPlayer'] | null; // TrumpPlayer
    players: NexusGenRootTypes['TrumpPlayer'][]; // [TrumpPlayer!]!
  }
  TrumpPack: { // field return type
    attributes: NexusGenRootTypes['TrumpAttribute'][]; // [TrumpAttribute!]!
    author: NexusGenRootTypes['TrumpPlayer']; // TrumpPlayer!
    cards: NexusGenRootTypes['TrumpCard'][]; // [TrumpCard!]!
    createdAt: any; // DateTime!
    description: string; // String!
    id: string; // ID!
    name: string; // String!
    updatedAt: any; // DateTime!
  }
  TrumpPlayer: { // field return type
    id: string; // ID!
    trumpGames: NexusGenRootTypes['TrumpGame'][]; // [TrumpGame!]!
    trumpGamesAtTurn: NexusGenRootTypes['TrumpGame'][]; // [TrumpGame!]!
    trumpPacks: NexusGenRootTypes['TrumpPack'][]; // [TrumpPack!]!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // field return type
    email: string; // String!
    id: string; // ID!
    name: string; // String!
    trumpPlayer: NexusGenRootTypes['TrumpPlayer'] | null; // TrumpPlayer
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneTrumpAttribute: { // args
      data: NexusGenInputs['TrumpAttributeCreateInput']; // TrumpAttributeCreateInput!
    }
    createOneTrumpCard: { // args
      data: NexusGenInputs['TrumpCardCreateInput']; // TrumpCardCreateInput!
    }
    createOneTrumpPack: { // args
      data: NexusGenInputs['TrumpPackCreateInput']; // TrumpPackCreateInput!
    }
    createOneUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
    startTrumpGame: { // args
      pack: string; // String!
      player1: string; // String!
      player2: string; // String!
    }
    uploadTrumpCardImage: { // args
      cardId: string; // ID!
      file?: any | null; // Upload
    }
  }
  Query: {
    trumpGames: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    trumpPacks: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    trumpPlayers: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  TrumpCard: {
    attributeValues: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  TrumpGame: {
    players: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  TrumpPack: {
    attributes: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    cards: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  TrumpPlayer: {
    trumpGames: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    trumpGamesAtTurn: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    trumpPacks: { // args
      after?: string | null; // ID
      before?: string | null; // ID
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Mutation" | "Query" | "Subscription" | "TrumpAttribute" | "TrumpAttributeValue" | "TrumpCard" | "TrumpGame" | "TrumpPack" | "TrumpPlayer" | "User";

export type NexusGenInputNames = "TrumpAttributeCreateInput" | "TrumpAttributeCreateManyWithoutAttributesInput" | "TrumpAttributeCreateOneWithoutAttributeInput" | "TrumpAttributeCreateWithoutPackInput" | "TrumpAttributeCreateWithoutTrumpAttributeValuesInput" | "TrumpAttributeValueCreateManyWithoutAttributeValuesInput" | "TrumpAttributeValueCreateManyWithoutTrumpAttributeValuesInput" | "TrumpAttributeValueCreateWithoutAttributeInput" | "TrumpAttributeValueCreateWithoutCardInput" | "TrumpAttributeValueWhereUniqueInput" | "TrumpAttributeWhereUniqueInput" | "TrumpCardCreateInput" | "TrumpCardCreateManyWithoutCardsInput" | "TrumpCardCreateOneWithoutCardInput" | "TrumpCardCreateWithoutAttributeValuesInput" | "TrumpCardCreateWithoutPackInput" | "TrumpCardWhereUniqueInput" | "TrumpGameCreateManyWithoutTrumpGamesAtTurnInput" | "TrumpGameCreateManyWithoutTrumpGamesInput" | "TrumpGameCreateWithoutPlayerAtTurnInput" | "TrumpGameCreateWithoutPlayersInput" | "TrumpGameWhereUniqueInput" | "TrumpPackCreateInput" | "TrumpPackCreateManyWithoutTrumpPacksInput" | "TrumpPackCreateOneWithoutPackInput" | "TrumpPackCreateWithoutAttributesInput" | "TrumpPackCreateWithoutAuthorInput" | "TrumpPackWhereUniqueInput" | "TrumpPlayerCreateManyWithoutPlayersInput" | "TrumpPlayerCreateOneWithoutAuthorInput" | "TrumpPlayerCreateOneWithoutPlayerAtTurnInput" | "TrumpPlayerCreateOneWithoutTrumpPlayerInput" | "TrumpPlayerCreateWithoutTrumpGamesAtTurnInput" | "TrumpPlayerCreateWithoutTrumpGamesInput" | "TrumpPlayerCreateWithoutTrumpPacksInput" | "TrumpPlayerCreateWithoutUserInput" | "TrumpPlayerWhereUniqueInput" | "UserCreateInput" | "UserCreateOneWithoutUserInput" | "UserCreateWithoutTrumpPlayerInput" | "UserWhereUniqueInput";

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "DateTime" | "Float" | "ID" | "Int" | "String" | "Upload";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}